config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :edit, :update, :new, :create]
  resources :stores, only: [:index, :show]
  resources :products, only: [:index, :show]
  
  root to: 'pages#home'
  delete '/delete_list', to: 'lists#destroy', as: 'delete_list'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/my_account', to: 'users#edit'
  patch '/my_account', to: 'users#update'
  delete '/delete_account', to: 'users#destroy', as: 'delete_account'
  post '/delete_product', to: 'lists#remove_product', as: 'delete_product'
  post '/add_product', to: 'lists#add_product'
  get '/filter_stores', to: 'stores#filter', as: 'filter_stores'
  get '/my_stores', to: 'stores#my_stores', as: 'my_stores'
  get '/my_products', to: 'products#my_products', as: 'my_products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_products
  has_many :products, through: :list_products

  validates :title, presence: true

  def add_list_product(product)
    ListProduct.create(list: self, product: product)
  end

  def filter_list(products)
    @stores = []
    all_stores = Store.all
    products.each do |product|
      all_stores.each do |store|
        if store.products.include?(product) && !@stores.include?(store)
          @stores << store
        end
      end
    end
    @stores
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :validate_list, only: [:show, :edit, :update]
  before_action :list_redirect, only: [:show, :edit]

  def index
    @user = User.find(session[:user_id])
    @lists = @user.lists
    if @lists == []
      @no_lists = "You don't have any lists."
    end

    render :index
  end

  # def show
  #   list_redirect
  # end
  #
  # def edit
  #   list_redirect
  # end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end


  def new
    @list = List.new
    render :new
  end

  #refactored creation of ListProduct into a method for list class
  def create
    @user = User.find(session[:user_id])
    @list = List.new(list_params)
    @list.user = @user
    if @list.save
      if request.referrer.include?("products/")
        @product = Product.find(session[:product_id])
        @list.add_list_product(@product)
        flash[:add_list] = "Saved"
        redirect_to @product and return
      end
      redirect_to lists_path
    else
      render :new
    end
  end

  def add_product
    @product = Product.find(session[:product_id])
    if params[:lists]
      @list = List.find(params[:lists][:list_id])
      @list.add_list_product(@product)
      redirect_to @product
      flash[:add_product] = " #{@product.name} added to #{@list.title}"
    end
  end

  def remove_product
    @list = List.find(session[:list_id])
    @product = Product.find(params[:id])
    @list_product = ListProduct.find_by(list: @list, product: @product)
    @list_product.delete
    redirect_to edit_list_path(@list)
  end

  def destroy
    @list = List.find(session[:list_id])
    @list.delete
    redirect_to '/'
  end

  private

  def validate_list
    @list = List.find(params[:id])
    @user = User.find(session[:user_id])
    if @list.user == @user
      @products = @list.products
    else
      @list = ""
      @products = []
    end
  end

  def list_params
    params.require(:list).permit(:title)
  end

  def list_redirect
    if @list == ""
      redirect_to '/lists'
    else
      session[:list_id] = @list.id
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
    
  def user_lists
    @user = User.find(session[:user_id])
    List.all.select {|list| list.user == @user}
  end
end

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <div class="input-group">
    <%= f.text_field :title %>
    <div class="input-group-append">
      <%= f.submit 'Save Title', class: "btn btn-outline-success" %>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="row">

  <div class="col">
    <h1 class="text-success">Edit your list:</h1>
      <%= render 'form', list: @list %>

      <ol class="list-group">
        <% @products.each do |product| %>
          <li class="mt-1 ml-5"> <%= link_to product.name, product %>
            <button class="btn">
              <%= link_to '', delete_product_path(:id => product.id), method: :post, class: 'fa fa-trash', style: 'color: black;' %>
            </button>
          </li>
        <% end %>
      </ol>
    <%= button_to 'Delete this list', delete_list_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-outline-danger mt-3 ml-3' %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="sm-container card">

  <div class=" lists-card">
      <div class="card-header">
        <h3><a class="text-success">Your Lists:</h3>
      </div>

      <div class="card-text ml-2 listed-lists">
        <ol style= >
          <% @lists.each do |list| %>
            <li><%= link_to list.title, list %></li>
          <% end %>
        </ol>

          <%= @no_lists %>
      </div>

      <div class="new-list">
          <%= button_to 'New List', '/lists/new', method: :get, class: 'btn btn-outline-success mb-3' %>
      </div>

    </div>


</div>

app/views/lists/new.html.erb
<div class="center">


<h1 class="text-success ">Make a new list:</h1>

<%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<h1 class="text-secondary"><%= @list.title %></h1>

<ol>
  <% @products.each do |product| %>
    <li> <%= link_to product.name, product %> </li>
    <p class="font-weight-light text-danger"><%= product.out_of_stock %></p>
  <% end %>
</ol>

<%= button_to 'Edit List', edit_list_path(@list), method: :get, class: 'btn btn-outline-warning' %>

<%= button_to 'Filter Stores by List', filter_stores_path, method: :get, class: 'btn btn-outline-primary' %>