config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :edit, :update, :new, :create]
  resources :stores, only: [:index, :show]
  resources :products, only: [:index, :show]
  
  root to: 'pages#home'
  delete '/delete_list', to: 'lists#destroy', as: 'delete_list'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/my_account', to: 'users#edit'
  patch '/my_account', to: 'users#update'
  delete '/delete_account', to: 'users#destroy', as: 'delete_account'
  post '/delete_product', to: 'lists#remove_product', as: 'delete_product'
  post '/add_product', to: 'lists#add_product'
  get '/filter_stores', to: 'stores#filter', as: 'filter_stores'
  get '/my_stores', to: 'stores#my_stores', as: 'my_stores'
  get '/my_products', to: 'products#my_products', as: 'my_products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists

  validates :name, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password

  def any_errors?
    self.errors.any?
  end

  def error_count
    self.errors.count
  end

  def error_messages
    self.errors.full_messages
  end

  def lists_count
    self.lists.count
  end

  #this method will return an array of products for a user.
  def products
    products = []
    self.lists.each do |list|
      list.products.each do |product|
        if !products.include?(product)
          products << product
        end
      end
    end
    products
  end

  #this method will return an array of all stores that a user's products are sold in
  def stores
    stores = []
    self.lists.each do |list|
      list.products.each do |product|
        product.stores.each do |store|
          if !stores.include?(store)
            stores << store
          end
        end
      end
    end
    stores
  end

  #condensed all 3 of the below methods from the original 6 methods
  def list_sample(element)
    if self.lists != []
      self.lists[element]
    end
  end

  def product_sample(element)
    if self.products != []
      self.products[element]
    end
  end

  def store_sample(element)
    if self.stores != []
      self.stores[element]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :validate_user, only: [:new, :create]
  before_action :set_params, only: [:edit, :update, :destroy]

  def update
    if @user.update(user_params) && params[:user][:password] == params[:user][:password_confirmation]
      redirect_to '/'
    else
      render :edit
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save && params[:user][:password] == params[:user][:password_confirmation]
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  def destroy
    @user.delete
    @user.lists.destroy_all
    session.delete :user_id
    redirect_to '/'
  end


private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_params
    @user = User.find(session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.any_errors? %>
  <div class="sign-errors login-flash" id="error_explanation">
    <h2>
      <%= pluralize(@user.error_count, "error") %>
      prohibited your account from being created:
    </h2>

    <ul>
    <% @user.error_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="center log-sign">

  <h1 class="main-head">Edit My Account</h1>

  <div class="row log-sign-field">

    <div class="col-md-12 col-md-offset-3">
        <%= form_for :user, url: '/my_account', method: :patch do |f| %>

          <div>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="mt-3">


            <%= f.submit 'Save', class: "btn btn-primary save"%>
          <% end %>

          <%= render 'errors' %>

       <%= button_to 'Delete My Account', delete_account_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-outline-danger', id: 'delete' %> 
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="login-container">
  <div class="center log-sign ">
    <h1 class="main-head">Sign Up: </h1>
    <div class="log-sign-field">
        <div class="col-md-12 col-md-offset-3">
          <%= form_for :user, url: '/signup' do |f| %>
            <div >
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div >
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div >
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div >
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div id="sign-submit">
              <%= f.submit "Sign Up", class: "btn btn-primary" %>
            <% end %>
            </div>
        </div>
    </div>
      <%= render 'errors' %>
  </div>
  <!-- 'errors' contained in div.sign-errors -->

</div>

app/views/users/show.html.erb
<h2> <%= @user.name %> </h2>

<h4> <%= @user.email %> </h4>